name: hackathonmaterial
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - 'assets/qrcode.png'
  fonts:
    - family: SFProDisplay
      fonts:
      - asset: assets/SFPRODISPLAYREGULAR.OTF
    - family: SFProDisplayBold
      fonts:
      - asset: assets/SFPRODISPLAYBOLD.OTF
    - family: ProductSanPro
      fonts:
      - asset: assets/ProSansBold.ttf
    - family: Takota
      fonts:
      - asset: assets/Takota.otf
  uses-material-design: true